# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Collection in Python
author: Neal Caren
logo: images/networks.png
email: neal.caren@unc.edu
description: >- # this means to ignore newlines until "baseurl:"
  A haphazard collection of methods for collecting social science data in Python.


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/nealcaren/collecting  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  # branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  extra_navbar: ""
  extra_footer: "University of North Carolina, Chapel Hill"

sphinx:
  config:
    html_show_copyright: false


launch_buttons:
  colab_url: "https://colab.research.google.com"
